### ISSUE TITLE
cp command on setup does not copy hidden files

### ISSUE THREAD

**Issue by Plsr** [timomeh/dotfiles#1]
I was looking at your documentation for using the dotfiles on a new machine (basically because I was lazy, but that's a different story). 

It looks like the command `cp -r ~/dotfiles-tmp/* ~` will not copy hidden files. According to [this](https://superuser.com/a/367303), it works with a dot at the end instead of the asterisk (`cp -r ~/dotfiles-tmp/. ~`), which I can confirm.

**Comment by timomeh** [comment]
Nice, thanks!
